name: release

on:
  push:
    branches:
      - input_total

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Cache cargo registry
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-build-cache
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/budget_buddy_terraform_deploy_role
          role-session-name: budget_buddy_terraform_deploy
          aws-region: eu-west-2
      - name: Deploy Terraform
        run: /
          cd terraform && terraform plan -out="plan" && terraform apply "plan"
      - name: Release lambda
        run: |
          pip install cargo-lambda
          cargo lambda build --release
          cargo lambda deploy budget_buddy
        env:
          AWS_DEFAULT_REGION: eu-west-2
